// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bottombar: typeof import('./components/layout/Bottombar.vue')['default']
    CardSetContent: typeof import('./components/content/CardSetContent.vue')['default']
    CardSetEditor: typeof import('./components/editors/CardSetEditor.vue')['default']
    GlossaryContent: typeof import('./components/content/GlossaryContent.vue')['default']
    GlossaryEditor: typeof import('./components/editors/GlossaryEditor.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    Input: typeof import('./components/inputs/Input.vue')['default']
    MaterialsContainer: typeof import('./components/MaterialsContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    UserPanel: typeof import('./components/layout/UserPanel.vue')['default']
  }
}

export {}
