// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Assets: typeof import('./components/modals/Assets.vue')['default']
    AssetsMenu: typeof import('./components/modals/AssetsMenu.vue')['default']
    AssetUpload: typeof import('./components/modals/AssetUpload.vue')['default']
    AssetView: typeof import('./components/modals/AssetView.vue')['default']
    Bottombar: typeof import('./components/layout/Bottombar.vue')['default']
    CardSetContent: typeof import('./components/content/CardSetContent.vue')['default']
    CardSetEditor: typeof import('./components/editors/CardSetEditor.vue')['default']
    Confirm: typeof import('./components/modals/Confirm.vue')['default']
    GlossaryContent: typeof import('./components/content/GlossaryContent.vue')['default']
    GlossaryEditor: typeof import('./components/editors/GlossaryEditor.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    Input: typeof import('./components/inputs/Input.vue')['default']
    InputModal: typeof import('./components/modals/InputModal.vue')['default']
    'InputModal copy': typeof import('./components/modals/InputModal copy.vue')['default']
    MaterialsContainer: typeof import('./components/MaterialsContainer.vue')['default']
    Modal: typeof import('./components/modals/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    UserPanel: typeof import('./components/layout/UserPanel.vue')['default']
  }
}

export {}
