// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Bottombar: typeof import('./components/Bottombar.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    MaterialsContainer: typeof import('./components/MaterialsContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    UserPanel: typeof import('./components/UserPanel.vue')['default']
  }
}

export {}
